### ISSUE TITLE
Compare Word and HTML content of BIPM SI brochure

### ISSUE THREAD

**Issue by anermina** [metanorma/bipm-si-brochure#10]
As requested in https://github.com/metanorma/bipm-si-brochure/issues/2#issuecomment-688592557.

**Comment by anermina** [comment]
@ronaldtse , could you please check my comment above and let me know whether any changes are required? 

Notes are also missing in YAML files. Should they be added to the files from cgpm-resolutions repository?

**Comment by ronaldtse** [comment]
@anermina I have sought clarification and will revert soon. Thanks!

**Comment by anermina** [comment]
And what I didn't report earlier because it seemed not to be relevant is that HTML contains more resolutions. When I started working with YAML files, I figured out it was important after all, since YAMLs contain all those resolutions. Some of them are in French, although this is an English version of the document, while some of them are in English, but just don't exist in Word version of the BIPM brochure.

**Comment by ronaldtse** [comment]
Replies from BIPM:

4. Appendix 1. Representation of resolution titles differ between the Word and the HTML version.
 
> Proposed action: [need clarification]

Keep the style of the titles in the SI brochure as they are. There is no need that they look the same way as the titles of the resolutions on the web page on the CGPM (I suppose that is where you took the HTML version from). Previous versions of the SI brochure were printed on paper and the same was initially planned for the 9th edition, although it was never done. Therefore the SI brochure has the style of a paper based document, whereas the HTML versions of the recommendations were directly designed for the web.
 
5. Appendix 1. Resolutions frequently refer to some external sources, which are explicitly mentioned in HTML, but these references are not explicit in the Word version.
 
> Proposed action: add explicit references in the Bibliography of the SI Brochure.
Let’s keep the text of the SI brochure for the moment as it is.

6. Appendix 1. Cross-references to other Resolutions in HTML is performed by citing the particular Resolution, while in Word it cites the Resolution plus the corresponding page number.

> Proposed action: If possible, we prefer directly linking the Resolution to the relevant section instead of displaying the page number of the Resolution to prevent confusion.

The page numbers in the Brochure are needed because they refer to another page of the same document. The HTML versions of the Resolutions have hyperlinks to other resolutions. Keep the page numbers.

7. Appendix 1. Some notes are missing in HTML.
 
> Proposed action: Keep the note, update HTML. (at the BIPM website).

Keep the note. We will consider to update the HTML.
 
8. Appendix 1. Resolution 3 of the 9th CGPM contains one note in Word and none in HTML.
 
> Proposed action: Add the note to HTML.

We will consider this.

9. Appendix 1. Some other parts of the text are also missing in HTML. For example, 9th CGPM contains one extra section after Resolution 3 in Word. That section is missing in HTML.
 
> Proposed action: Add extra Resolution back to HTML version.

The text on the adoption of the term “degree Celsius” is not part of Resolution 3 of 1948. It is a separate decision of the CGPM and should not be added to the HTML text of the resolution.

10. Appendix 1. Some notes slightly differ. Example given below is from Resolution 6 of the 10th CGPM.
 
> Proposed action: Adopt the HTML text here.

Agreed. Capital K also in the brochure.

**Comment by anermina** [comment]
Thank you, @ronaldtse !

This is clear, but it opens a question whether we should also align YAML files with the printed version of the document. YAML files currently contain information from HTML (except from the notes). If we want to reproduce the same content as in Word/PDF using YAMLs, I believe changes need to be applied.
