### ISSUE TITLE
Brochure review: apostrophes vs prime symbols

### ISSUE THREAD

**Issue by manuel489** [metanorma/bipm-si-brochure#102]
*In relation to https://github.com/metanorma/bipm-si-brochure/issues/87*

Shouldn't apostrophes be rendered as prime symbols in math environment?

![issue-apostrophe](https://user-images.githubusercontent.com/33627611/111412270-7f1f7200-86b2-11eb-8aa1-56cdf09c1aca.PNG)

Single Prime symbol: `&#x2032;`
Double Prime symbol: `&#x2033;`

**Comment by opoudjis** [comment]
Yes they should. To be more explicit: the asciimath parser is meant to convert apostrophes into primes. And as it turns out, it has; looking at the XML for the MathML generated from that paragraph, I see:

````
<stem type="MathML"><math xmlns="http://www.w3.org/1998/Math/MathML"><mstyle mathvariant="italic"><mi>V</mi></mstyle><mo>&#8242;</mo><mfenced open="(" close=")"><mrow><mstyle mathvariant="italic"><mi>&#955;</mi></mstyle></mrow></mfenced></math></stem>,
````

&#8242; is indeed a prime. Some fonts may be rendering them to look more like apostrophes, which is regrettable, but the text is correct.
