### ISSUE TITLE
BIPM review: ToC missing content after Appendix 4

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#113]
> The following text is missing...
> Part 1. The historical development of the realization of SI units 202
> Part 2. The historical development of the International System 204
> Part 3. Historical perspective on the base units 206

<img width="605" alt="image" src="https://user-images.githubusercontent.com/11865/121832103-d954c100-ccfb-11eb-9615-b2ccb02d349f.png">

**Comment by Intelligent2013** [comment]
@ronaldtse we could show 2nd-level annex subsections in the ToC for `Appendix 4`, at first glance xml allows to do it:
```xml
<annex id="_..." obligation="normative">
	<title>
		<strong>Appendix 4</strong>.<tab/>
		<strong>Historical notes on the development of the International System of Units and its base units</strong>
	</title>
	<clause id="_..." obligation="normative">
		<title depth="2">4.1.<tab/>Part 1. The historical development of the realization of SI units <bookmark to="realization_unit-3" id="_..."/>
		</title>
```

Resulted PDF:
![image](https://user-images.githubusercontent.com/5559926/121842072-55dda480-cce8-11eb-9801-d13d070de3bf.png)

BUT `Appendix 1` also has 2nd-level subsections (original PDF doesn't contain subsections in ToC for Appendix 1):
```xml
<annex id="_..." obligation="normative">
		<title>
			<strong>Appendix 1</strong>.<tab/>
			<strong>Decisions of the CGPM and the CIPM</strong>
		</title>
		<p ...</p>
		<pagebreak/>
		<clause id="_..." obligation="normative">
			<title depth="2">1.1.<tab/>Table of Contents of Appendix 1</title>
			...
		</clause>
		<clause id="cgpm1st1889" obligation="normative">
			<title depth="2">1.2.<tab/>1st CGPM, 1889</title>
		</clause>
		<clause id="cgpm3rd1901" obligation="normative">
			<title depth="2">1.3.<tab/>3rd CGPM, 1901</title>
		...
		</clause>
```
Resulted PDF:
![image](https://user-images.githubusercontent.com/5559926/121842261-c5ec2a80-cce8-11eb-86c9-4e8fadcdc921.png)

So, xslt can't distinguish one case from another.

This issue was mentioned in https://github.com/metanorma/bipm-si-brochure/issues/47.

**Comment by ronaldtse** [comment]
This treatment was already officially approved by Michael Stock of BIPM that for consistency reasons we don't need to show inner items of Appendix 4. So we don't need to do anything.

**Comment by ronaldtse** [comment]
Confirmed from Michael Stock of BIPM:

> I had replied on 15 October that the treatment of the subsections of Appendices 1 and 4 could be aligned in the sense that the subsections are not displayed in the ToC.  [...] It is one of these changes from the present pdf file which we have to accept for the sake of consistency.
