### ISSUE TITLE
BIPM review: extra vertical space (or line break)

### ISSUE THREAD

**Issue by manuel489** [metanorma/bipm-si-brochure#126]
*In relation to https://github.com/metanorma/bipm-si-brochure/issues/112*

From BIPM:
![issue11](https://user-images.githubusercontent.com/33627611/121960425-10df5f80-cd34-11eb-98e7-1641a9572b11.PNG)

There is extra vertical space between the paragraphs shown above.

**Comment by Intelligent2013** [comment]
Extra vertical space arises because there is side note at right side:

![image](https://user-images.githubusercontent.com/5559926/122260849-6bb3bb00-cedc-11eb-8e5b-02b2c158cf0d.png)

I can't to do anymore here. Workaround solution for processing side nodes was very complicated, and if solve this concrete issue, then another issues will occur again.

**Comment by ronaldtse** [comment]
This is not to be fixed because it is a feature, this is correct.

**Comment by ronaldtse** [comment]
This was already agreed upon with Michael Stock of BIPM in https://github.com/metanorma/mn-native-pdf/issues/268#issuecomment-714524889 .

**Comment by ronaldtse** [comment]
From Michael Stock of BIPM:

> Agreed.

Nothing to be done here.
