### ISSUE TITLE
BIPM review: Quoted resolution content as numbered list items

### ISSUE THREAD

**Issue by manuel489** [metanorma/bipm-si-brochure#131]
*In relation to https://github.com/metanorma/bipm-si-brochure/issues/112*

From BIPM:
![issue16](https://user-images.githubusercontent.com/33627611/121971712-66713780-cd47-11eb-8c82-e9d1dd33253c.PNG)

According to BIPM:
1. Numbered list items should be enclosed in parentheses
2. Paragraph of side notes should be left-aligned.

**Comment by manuel489** [comment]
Also there is this:
![issue24-1](https://user-images.githubusercontent.com/33627611/122252709-8dd81980-ce99-11eb-8737-9221fc1d592e.PNG)

Original version:
![issue24-2](https://user-images.githubusercontent.com/33627611/122252749-94ff2780-ce99-11eb-866f-b2a8b54efada.PNG)

**Comment by ronaldtse** [comment]
> 1. Numbered list items should be enclosed in parentheses

Not true - this specific comment only applies to this particular quote.

In fact, this is not an important point because the original text is this:

<img width="706" alt="Screenshot 2021-06-17 at 2 05 19 PM" src="https://user-images.githubusercontent.com/11865/122340613-124b9a80-cf75-11eb-9740-45bf6b09ae3d.png">

So the original text was an unnumbered list, not a numbered list.

We will need to clarify with BIPM.

> 2. Paragraph of side notes should be left-aligned.

OK.

> Also there is this:

<img width="798" alt="Screenshot 2021-06-17 at 2 07 04 PM" src="https://user-images.githubusercontent.com/11865/122340803-50e15500-cf75-11eb-9fd4-57ffbe73154a.png">

I'm not sure how the original resolution is presented. Look at this:
https://www.bipm.org/en/committees/ci/cipm/42-1946/resolution-2

<img width="696" alt="Screenshot 2021-06-17 at 2 08 20 PM" src="https://user-images.githubusercontent.com/11865/122340939-7e2e0300-cf75-11eb-9cf2-82154c7766cc.png">

So on the website it is "01" but in the document it has to be "(A)"? That's not right.

**Comment by ronaldtse** [comment]
Original resolution was presented like this:
https://www.govinfo.gov/content/pkg/GOVPUB-C13-8e9f1926a41baee80183b02744114d25/pdf/GOVPUB-C13-8e9f1926a41baee80183b02744114d25.pdf
<img width="1099" alt="Screenshot 2021-06-17 at 2 37 22 PM" src="https://user-images.githubusercontent.com/11865/122344605-8d16b480-cf79-11eb-92be-8396db877c48.png">

**Comment by ronaldtse** [comment]
I'm going to split this ticket because the two issues are unrelated.

**Comment by ronaldtse** [comment]
Ticket has been split.

**Comment by ronaldtse** [comment]
@Intelligent2013 the only thing that needs to be done is:
> 2. Paragraph of side notes should be left-aligned.

We are seeking feedback from BIPM on the numbering.

**Comment by Intelligent2013** [comment]
> 2. Paragraph of side notes should be left-aligned.

Fixed.
![image](https://user-images.githubusercontent.com/5559926/122455004-9a04c980-cfb4-11eb-9fd9-211c56a20258.png)

**Comment by ronaldtse** [comment]
From Michael Stock of BIPM:

> Your comment regarding the original form in the 1995 CGPM resolution 8 is a good one. Is it possible to remove the numbers and just have two bullet point, as in the reproduction of the resolution in Appendix 1? Otherwise, using “(1)” instead of “1.” is not a big issue.

We should use the unnumbered list "bullet" instead of "1." in this note.

@manuel489 can you help fix this? Thanks!

**Comment by ronaldtse** [comment]
Shows like this now: 

<img width="146" alt="Screenshot 2021-07-06 at 12 08 40 PM" src="https://user-images.githubusercontent.com/11865/124540923-f429d980-de52-11eb-8f10-5cebc29046d3.png">

But the bullet points seem a bit misaligned with text, and also a bit too big for the text font size. Can we adjust this? Thanks.

**Comment by ronaldtse** [comment]
@Intelligent2013 keeping it open for you.

**Comment by Intelligent2013** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/5559926/124593831-c733f180-de67-11eb-8daa-d2ec0018c77d.png)

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 !
