### ISSUE TITLE
BIPM final review: presentational errors to be fixed

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#190]
To @metanorma/editors 

This issue follows #189 to fix the remaining presentational errors.

The original excel sheet:
* [20220915-bipm-si-brochure-final-review.xlsx](https://github.com/metanorma/bipm-si-brochure/files/9573309/20220915-bipm-si-brochure-final-review.xlsx)

NOTE: The equations don't look right on GitHub, you need to check the Excel file.

Number | Page | Clause/paragraph | Comment
-- | -- | -- | --
  |   |   |  
1 | 8 | first line of ToC | Superscript for the "e" = 9e
2 | 10 | header | Superscript for the "e" = 9e
3 | 10 | 4. paragraph, line 4 | remove the space between "SI" and the full stop.
4 | 10 | 4. paragraph, line 13 | remove the additional space between "SI" and "et"
5 | 11 | list of annexes | missing vertical spaces between the four list items
6 | 11 | note | note not aligned on right side; insert a vertical space between the two paragraphs
7 | 11 | signatures | insert a space between initial and surname: "B. Inglis", "J. Ullrich"
8 | 11 | Note | Add a space before and after the colon "NOTE : La…", general rule for the French text: insert a space before the colon
9 | 13 | 1.2, last line | Remove the space before the full stop
10 | 15 | Table 1 | increase width of 1. column to have less line breaks in the names of constants, also applies to several other tables
11 | 18 | last equation | last group should have four decimals to avoid single decimal (see paragraph 5.4.4), also in other equations
12 | 20 | second last paragraph on kelvin | The hyperlink should be to the French page:                                            https://www.bipm.org/fr/committees/ci/cipm/78-1989/resolution-5                                 general rule: In the French text, hyperlinks to recommendations or resolutions should go to the French versions, not the English; en to be replaced by fr in the weblink
13 | 24 | third paragraph | Remove the space before the full stop
14 | 32 | side note | Remove the space before the full stop
15 | 36 | example 1 | remove ":" at the end of  title
16 | 37 | example 1 | add spaces in "30° 22' 8'"
17 | 38 | 5.4.6, second paragraph | Remove the space before the full stop at the end
18 | 47 | 3rd CGPM | "CGPM Résolution 1" should be replaced by "Résolution 1 de la CGPM" This is the case for all occurrences in Appendix 1 (CGPM Résolution xx = Résolution xx de la CGPM). Idem for CIPM Resolutions
19 | 47 | "sanctionne" | enumeration 1., 2., 3. replaced by a), b), c); in the English text, the numbers are maintained, use numbers also in French
20 | 48 | last side note | replace "CGPM Réunion 9" by   "9e réunion de la CGPM", use this scheme consistenty, also for CIPM meetings
22 | 49 | second side note | delete "Note", for consistency with other numbered side notes which don't start with "note"
21 | 49 | Section B, entry for ampere | "1 mètre" should not be split over two lines, same for "1 coulomb" in the entry for the farad and "1 volt" for the weber
22 | 52 | 10e CGPM 1954, side note | Add brackets and the page reference for consistency:  (Résolution 4, voir p. 59)
23 | 53 | CIPM 1956, text after "décide" | last group should have four decimals to avoid single decimal (see paragraph 5.4.4), also in other equations
24 | 54 | CGPM Resolution 9, text after "ratifie" | last group should have four decimals to avoid single decimal (see paragraph 5.4.4), also in other equations
25 | 57 | 1. side note | avoid opening parenthesis at end of line
26 | 59 | Resolution 3, text following "considérant" | "CIPM Réunion 51" should be replaced by "51e réunion du CIPM"
27 | 60 | first paragraph | 1/600 000 mètre should be on the same line; same thing for "101 325 newtons"
28 | 61 | Note | add a space before the ":"
29 | 63 | Note | add a space before the ":"
30 | 73 | 3. list item after recommande | avoid openening parenthesis at end of line
31 | 76 | last bullet point after "décide" | This opening bracket should be on the following line
32 | 77 | first bullet point after "recommande" | The 87 should be before the Rb rather than on top
33 | 77 | third bullet after "recommande" | Add a space before the (F = 0) or (F = 2) bits (4 times in that recommandation)
34 | 77 | last bullet point after "décide" | The 87 should be before the Sr rather than on top
35 | 80 | fourth bullet after "recommande" | A space is needed before (F = ...)  (4 times on that page)
36 | 80 | side note (1) | The place of this side note follows the general scheme to anchor all side notes at the beginning of the section. In this case, the use of the reference is two pages later. Is there a simple way to bring the note closer to this place?
37 | 86 | second indented bullet | A space is needed before (F = ...)  (2 times )
38 | 87 | 1. bullet | remove space before and after  "CODATA"
39 | 88 | first bullet | Add a space (two times) before (F = ...)
40 | 96 | A4.2 | In Appendix 4, for the references to CGPM resolution:                                                                                   - Delete the year and Resolution (here 1948, Résolution 6 ;)                                                         - Change "CGPM Résolution xx" by "Résolution xx de la CGPM"                                                                         - Replace the hyperlink by the French one (/fr/ instead of /en/ at the beginning)
41 | 120 |   | missing vertical spaces between the four list items
42 | 120 |   | note not aligned on right side; insert a vertical space between the two paragraphs
43 | 127 | last equation | last group should have four decimals to avoid single decimal (see paragraph 5.4.4)
44 | 128 | second equation | last group should have four decimals to avoid single decimal (see paragraph 5.4.4)
45 | 128 |   | There seems to be hidden text (delta(nu)) in white colour, visible in front of the "T" of the word "Draft" in the background. The same exists on many other pages.
46 | 128 | last equation | last group should have four decimals to avoid single decimal (see paragraph 5.4.4)
47 | 129 | first equation | Why is the full stop so close to the symbol?
48 | 130 | last equation | last group should have four decimals to avoid single decimal (see paragraph 5.4.4)
49 | 140 | footnote (d) | Add hyperlinks to Metrologia citations.Reference should be "16th CGPM (1979, Resolution 6)
50 | 142 | 5.2, second paragraph | Insert hyperlinks to CGPM resolutions
51 | 145 | example 1 | add spaces in "30° 22' 8'"
52 | 145 | 5.4.4, example 1 | The same minus sign should be used in the line above and in the example
53 | 147 | 5.4.8, second paragraph, line 2 | Insert a space after the comma
54 | 150 | ToC, CIPM 2001 | Opening double quotes
55 | 161 | first line | last group should have four decimals to avoid single decimal (see paragraph 5.4.4), also in other equations
56 | 162 | first line after "ratifies" | last group should have four decimals to avoid single decimal (see paragraph 5.4.4), also in other equations
57 | 169 | last line | Closing double quotes
58 | 184 | first bullet after "recommends" | The 87 should be before the Rb rather than on top
59 | 184 | last bullet after "recomends" | The 87 should be before the Sr rather than on top
60 | 200 | A4.1 | reviews format of references to CGPM resolutions in Appendix 4

**Comment by manuelfuenmayor** [comment]
@ronaldtse the provided Excel sheet does not correspond to the table shown in the description.

**Comment by manuelfuenmayor** [comment]
> 1 | 8 | first line of ToC | Superscript for the "e" = 9e
2 | 10 | header | Superscript for the "e" = 9e

[Delegated](https://github.com/metanorma/metanorma-bipm/issues/204)

> 5 | 11 | list of annexes | missing vertical spaces between the four list items
41 | 120 |   | missing vertical spaces between the four list items

[Delegated](https://github.com/metanorma/metanorma-bipm/issues/197)

> 6 | 11 | note | note not aligned on right side; insert a vertical space between the two paragraphs
42 | 120 |   | note not aligned on right side; insert a vertical space between the two paragraphs

[Delegated](https://github.com/metanorma/metanorma-bipm/issues/198)


> 8 | 11 | Note | Add a space before and after the colon "NOTE : La…", general rule for the French text: insert a space before the colon

[Delegated](https://github.com/metanorma/metanorma-bipm/issues/201)


> 10 | 15 | Table 1 | increase width of 1. column to have less line breaks in the names of constants, also applies to several other tables

This issue was fixed already.


> 11 | 18 | last equation | last group should have four decimals to avoid single decimal (see paragraph 5.4.4), also in other equations
23 | 53 | CIPM 1956, text after "décide" | last group should have four decimals to avoid single decimal (see paragraph 5.4.4), also in other equations
24 | 54 | CGPM Resolution 9, text after "ratifie" | last group should have four decimals to avoid single decimal (see paragraph 5.4.4), also in other equations
43 | 127 | last equation | last group should have four decimals to avoid single decimal (see paragraph 5.4.4)
44 | 128 | second equation | last group should have four decimals to avoid single decimal (see paragraph 5.4.4)
46 | 128 | last equation | last group should have four decimals to avoid single decimal (see paragraph 5.4.4)
48 | 130 | last equation | last group should have four decimals to avoid single decimal (see paragraph 5.4.4)
55 | 161 | first line | last group should have four decimals to avoid single decimal (see paragraph 5.4.4), also in other equations
56 | 162 | first line after "ratifies" | last group should have four decimals to avoid single decimal (see paragraph 5.4.4), also in other equations

[Delegated](https://github.com/metanorma/metanorma-bipm/issues/205)


> 12 | 20 | second last paragraph on kelvin | The hyperlink should be to the French page:                                            https://www.bipm.org/fr/committees/ci/cipm/78-1989/resolution-5                                 general rule: In the French text, hyperlinks to recommendations or resolutions should go to the French versions, not the English; en to be replaced by fr in the weblink

[Delegated](https://github.com/metanorma/metanorma-bipm/issues/199)


> 17 | 38 | 5.4.6, second paragraph | Remove the space before the full stop at the end

The additional space is added by the X math symbol.


> 18 | 47 | 3rd CGPM | "CGPM Résolution 1" should be replaced by "Résolution 1 de la CGPM" This is the case for all occurrences in Appendix 1 (CGPM Résolution xx = Résolution xx de la CGPM). Idem for CIPM Resolutions
20 | 48 | last side note | replace "CGPM Réunion 9" by   "9e réunion de la CGPM", use this scheme consistenty, also for CIPM meetings
26 | 59 | Resolution 3, text following "considérant" | "CIPM Réunion 51" should be replaced by "51e réunion du CIPM"

[Delegated](https://github.com/metanorma/metanorma-bipm/issues/195)


> 19 | 47 | "sanctionne" | enumeration 1., 2., 3. replaced by a), b), c); in the English text, the numbers are maintained, use numbers also in French

[Delegated](https://github.com/metanorma/metanorma-bipm/issues/200)


> 28 | 61 | Note | add a space before the ":"
29 | 63 | Note | add a space before the ":"

[Delegated](https://github.com/metanorma/metanorma-bipm/issues/201)


> 36 | 80 | side note (1) | The place of this side note follows the general scheme to anchor all side notes at the beginning of the section. In this case, the use of the reference is two pages later. Is there a simple way to bring the note closer to this place?

[Delegated](https://github.com/metanorma/metanorma-bipm/issues/202)

> 45 | 128 |   | There seems to be hidden text (delta(nu)) in white colour, visible in front of the "T" of the word "Draft" in the background. The same exists on many other pages.

I don't see the issue in this part. No action taken on this request.


> 49 | 140 | footnote (d) | Add hyperlinks to Metrologia citations.Reference should be "16th CGPM (1979, Resolution 6)

Have published a question about this request in https://github.com/metanorma/bipm-si-brochure/issues/199.


> 54 | 150 | ToC, CIPM 2001 | Opening double quotes
57 | 169 | last line | Closing double quotes

[Delegated](https://github.com/metanorma/metanorma-bipm/issues/203)



All other issues are fixed by markup in https://github.com/metanorma/bipm-si-brochure/pull/200.

**Comment by ronaldtse** [comment]
Closing this since the rest has been made individual tickets:

* [ ] https://github.com/metanorma/metanorma-bipm/issues/195

* [ ] https://github.com/metanorma/metanorma-bipm/issues/197

* [ ] https://github.com/metanorma/metanorma-bipm/issues/198

* [ ] https://github.com/metanorma/metanorma-bipm/issues/199

* [ ] https://github.com/metanorma/metanorma-bipm/issues/200

* [ ] https://github.com/metanorma/metanorma-bipm/issues/201

* [ ] https://github.com/metanorma/metanorma-bipm/issues/202

* [ ] https://github.com/metanorma/metanorma-bipm/issues/203

* [ ] https://github.com/metanorma/metanorma-bipm/issues/204

* [ ] https://github.com/metanorma/metanorma-bipm/issues/205
