### ISSUE TITLE
Displaying fetched non-ASCII characters

### ISSUE THREAD

**Issue by anermina** [metanorma/bipm-si-brochure#203]
Rendering non-ASCII characters doesn't work correctly. Currently, we get these characters displayed the same as they are fetched (no translation is performed).
````
bundle exec relaton fetch "BIPM Metrologia 55 1 L13"
...
 <contributor>
    <role type="author"/>
    <person>
      <name>
        <completename language="en" script="Latn">de Mirand{\'{e}}s, Estefan{\'{\i}}a</completename>
      </name>
    </person>
  </contributor>
````
![image](https://user-images.githubusercontent.com/55683568/191350861-329212b2-04fb-4f48-9443-2031fbe9930c.png)

**Comment by opoudjis** [comment]
https://github.com/relaton/relaton-bipm/issues/40

Andrew is going away for a week, but this is a source data issue, Relaton should be publishing data in UTF-8.

**Comment by ronaldtse** [comment]
This issue requires Relaton to deal with BibTeX parsing and semantics. As you remember the `{...}` means that capitalization should not be changed for the text in between. We've never dealt with those and will need to.

In any case, this issue is not part of the SI Brochure, this is for the MEPs, so should not be affected by the milestone.

**Comment by opoudjis** [comment]
Removed milestone marker.

**Comment by opoudjis** [comment]
Has been fixed in latest version of relaton-bipm
