### ISSUE TITLE
Unable to install dependencies

### ISSUE THREAD

**Issue by andrew2net** [metanorma/bipm-si-brochure#206]
@opoudjis is there a reason the line is commented out? The relaton-data-bipm fails to build the bipm-si-brochure because it fails to install dependencies.
https://github.com/metanorma/bipm-si-brochure/blob/47677fc1ef1ed42d9dc65a5c05f1abe6f30d7697/Gemfile#L9

**Comment by opoudjis** [comment]
````
#if File.exist? "Gemfile.devel"
  #eval File.read("Gemfile.devel"), nil, "Gemfile.devel" # rubocop:disable Security/Eval
#end
````

This line allows an alternate Gemfile.devel to be read in, in order to override the Gemfile during testing with instances of gems fetched directly from github.

But I'm not seeing what difference it makes to comment it or not: my "bundle update" currently works fine.

I've reinstated 

````
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}" }
````

let me know if that takes care of it.
