### ISSUE TITLE
BIPM requested fixes 7: bibliography items authorship rendering inconsistency

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#227]
From Michael Stock:

The majority of the Metrologia references are given with the author initial before the author name, whereas [107], [108] and [108] include the full first name rather than the initial (Andrew rather than A) and the last two [110, 111] list the initials after the surnames.

**Comment by anermina** [comment]
This issue is related to the following references:
- BIPM Metrologia 41 1 99
- BIPM Metrologia 43 1 175
- BIPM Metrologia 44 1 97
- BIPM Metrologia 52 1 155
- BIPM Metrologia 56 2 022001

It can be seen that these references use `forename` + `surname` structure (BIPM Metrologia 52 1 155, BIPM Metrologia 56 2 022001):
````
    <role type="author"/>
    <person>
      <name>
        <forename language="en" script="Latn">Michael</forename>
        <surname language="en" script="Latn">Stock</surname>
      </name>
````
or include a full name under `surname` (BIPM Metrologia 41 1 99, BIPM Metrologia 43 1 175, BIPM Metrologia 44 1 97):
````
    <role type="author"/>
    <person>
      <name>
        <surname language="en" script="Latn">Andrew Wallard</surname>
      </name>
````

Michael refers to the references that include initials and the surname under the `surname` as the most common ones (e.g. BIPM Metrologia 40 2 103):
````
    <role type="author"/>
    <person>
      <name>
        <surname language="en" script="Latn">T J Quinn</surname>
      </name>
````

@andrew2net please share your thoughts.

**Comment by opoudjis** [comment]
This will need the initials separated out, and Relaton has mechanisms for expressing initials separately...

**Comment by andrew2net** [comment]
@ronaldtse the rawdata-data-metrologia dataset contains a lot of inconsistent surnames and forenames. For example there are:

- surname: "van der Veen" with given name "Adriaan M H"
- surname: "Berg" with given name "Robert F"
- full name in surname: "David W Allan", "W R G Kem", ""A De Marchi", "A de Marchi", "L van der Zwan", "K v Klitzing", "J -M Chartier", "R B Lee III", "P de la Court", and "Comité International des Poids et Mesures"

And many other variants such as double names with or without dash, affixes in surname or given name.
I think the best we can do is concatenate given name + surname and save result into full name.

**Comment by andrew2net** [comment]
Fixed by concat given name and surname
