### ISSUE TITLE
BIPM requested fixes 8: French version links to meetings in Resolutions should be to the French version

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#228]
From Michael Stock:

For the links **in the text** to the meetings and Resolutions in the French version (see for example p.40, p.102), the links should contain /fr/ in place of /en/

**Comment by anermina** [comment]
I cannot reproduce this. All the links on pages 40 and 102 point to the `/fr/` version.

![image](https://github.com/metanorma/bipm-si-brochure/assets/55683568/31ad8aea-5ff3-41d6-8107-08a8bbc60190)

However, after checking the entire document, I did find that Résolution du CIPM (1879) uses a link that points to the English instead of the French version.
![image](https://github.com/metanorma/bipm-si-brochure/assets/55683568/1f5a5626-6783-44ff-aa45-7c4ba50e9bf2)

URI is missing for French. Ping @andrew2net 
````
  <fetched>2024-02-23</fetched>
  <title format="text/plain" language="en" script="Latn">Signes abréviatifs pour les poids et mesures métriques</title>
  <uri type="citation" language="en" script="Latn">https://www.bipm.org/en/committees/ci/cipm/4-1879/resolution-</uri>
  <uri type="src" language="en" script="Latn">https://raw.githubusercontent.com/metanorma/bipm-data-outcomes/main/cipm/meetings-en/meeting-4.yml</uri>
  <uri type="src" language="fr" script="Latn">https://raw.githubusercontent.com/metanorma/bipm-data-outcomes/main/cipm/meetings-fr/meeting-4.yml</uri>
  <uri type="pdf">https://www.bipm.org/documents/20126/17315032/CIPM4.pdf/47e647d4-26c2-d3d6-b367-e749fb22b261</uri>
  <docidentifier type="BIPM" primary="true">CIPM RES (1879)</docidentifier>
````

**Comment by andrew2net** [comment]
The `relaton-bipm` takes English version from `cipm/meetings-en/meeting-4.yml` and French version `cipm/meetings-fr/meeting-40.yml`. You can see that page 40 in English version contains French texts but English link. French version doesn't have page 40 at all.
I'm sure we need to fix this issue in the `bipm-data-outcomes dataset`.

**Comment by andrew2net** [comment]
@anermina Let me explain. The relaton-bipm takes bipm-data-outcomes documents from the https://github.com/metanorma/bipm-data-outcomes repo. English and French versions of documents in the repo are in separate folders. For CIPM docs the folders are https://github.com/metanorma/bipm-data-outcomes/tree/main/cipm/meetings-en and https://github.com/metanorma/bipm-data-outcomes/tree/main/cipm/meetings-fr respectively.

It seems the files I mentioned are already fixed. However the "CIPM RES (1879)" still doesn't have a French link. I'll check that cause the problem.

**Comment by andrew2net** [comment]
@anermina the "CIPM RES (1879)" is copmosed from https://github.com/metanorma/bipm-data-outcomes/blob/main/cipm/meetings-en/meeting-4.yml and https://github.com/metanorma/bipm-data-outcomes/blob/main/cipm/meetings-fr/meeting-4.yml files. The English file have resolution but the French file doesn't.
So the French file needs to be fixes. I see @webdev778 created the file. Let's ask him for help.

**Comment by andrew2net** [comment]
Same issue with these files
https://github.com/metanorma/bipm-data-outcomes/blob/main/jcrb/meetings-fr/meeting-44.yml
https://github.com/metanorma/bipm-data-outcomes/blob/main/jcrb/meetings-fr/meeting-45.yml
https://github.com/metanorma/bipm-data-outcomes/blob/main/jcrb/meetings-fr/meeting-46.yml

**Comment by anermina** [comment]
Thank you, @andrew2net! I have opened a new ticket (https://github.com/metanorma/bipm-data-outcomes/issues/32) to address this issue. This one will remain open to track the remaining issues related to the BIPM SI Brochure.

**Comment by ronaldtse** [comment]
> @anermina the "CIPM RES (1879)" is copmosed from https://github.com/metanorma/bipm-data-outcomes/blob/main/cipm/meetings-en/meeting-4.yml and https://github.com/metanorma/bipm-data-outcomes/blob/main/cipm/meetings-fr/meeting-4.yml files. The English file have resolution but the French file doesn't. So the French file needs to be fixes. 

Now I see what you mean. The BIPM has removed the resolution content from the website entirely, so English and French are both empty.

This means we need to manually override the scraped content. This is not good.

**Comment by ronaldtse** [comment]
Update: All BIPM issues must be fully addressed by 2024-12-18.

**Comment by ronaldtse** [comment]
Wait, something is wrong in my copy. I don't even see the rendered names of the resolutions?

<img width="638" alt="Screenshot 2024-12-18 at 8 43 18 PM" src="https://github.com/user-attachments/assets/9d1f3fec-fe99-405b-95a7-9f53dc13f07d" />

**Comment by opoudjis** [comment]
I've found the issue and it's a doozie.

Collection processing, right after the Semantic XML is generated, rewrite erefs preemptively to links, if a citation URL is available for that bibliographic reference: collection/xrefprocess/xrefprocess.rb, eref_to_internal_eref1().

However, Presentation XML processing, which is still to happen, regenerates the citeas attribute of erefs, and populates it into the eref if it is empty. It isn't getting to these collection-postprocessed erefs, because they have already been converted to URLs.

Those erefs rewritten as links are still identifiable as such, from having a citeas and a bibitemid attribute. So when I find them in Presentation XML, I will not only include them in citeas regeneration, but also will populate their content with the citeas attribute if they are empty. The result will be the same as if they were erefs that were only rewritten into links later on in processing.

**Comment by opoudjis** [comment]
In addition, preemptively resolved erefs to citation URL need to be selecting for the correct language in metanorma collections, where there are language-specific URLs.

**Comment by manuelfuenmayor** [comment]
> ...I did find that Résolution du CIPM (1879) uses a link that points to the English instead of the French version.

Fix confirmed:

![fixed-ref-1879](https://github.com/user-attachments/assets/ed626fd9-beca-4bb1-871b-d06434f4a560)
