### ISSUE TITLE
BIPM requested fixes 10: "Milton J" should be "Milton M"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#230]
From Michael Stock:

The very last reference (no. 112 in the English text, no.111 in the French text) has a typo: it should be Milton M not Milton J.

**Comment by anermina** [comment]
The fetched value is as follows (BIPM Metrologia 56 2 022001):
````
      <name>
        <forename language="en" script="Latn" initial="J">Martin</forename>
        <forename initial="T"/>
        <surname language="en" script="Latn">Milton</surname>
      </name>
````

Ping @andrew2net

**Comment by opoudjis** [comment]
`forename/@initial` is the canonical initial of *that* forename, not another one. I use it if present, but J does not stand for Martin. So if the name is Martin J Milton, I would expect to see

````
<forename>Martin</forename>
<forename initial="J"/>
<surname>Milton</surname>
````

or at most

````
<forename initial="M">Martin</forename> # but by default I use the first letter anyway
<forename initial="J"/>
<formatted-initials>M</formatted-initials> # do not use M J
<surname>Milton</surname>
````

**Comment by andrew2net** [comment]
@ronaldtse I've checked the source dataset. It has inconsistency in person names:

- Sometimes full names are placed in the surname element and can contain initials, double names, suffixes, and other affixes. For example "Stephen Jarvis Jr", "W E de Bolle", "M-T Niatel".
- Sometimes the affixes are placed in the given-names with forename and initials. For example "Julian C J", "Adriaan M H van der"

I don't see staring way to correct parse all the cases. Isn't it a good idea just concatenate given name and surname save them as a full name string?

**Comment by ronaldtse** [comment]
@andrew2net for "source dataset" did you mean the IOP Metrologia XML, which has that article like this?
* https://iopscience.iop.org/article/10.1088/1681-7575/ab0013/meta

The source XML is:
```xml
<contrib contrib-type="author" xlink:type="simple">
  <contrib-id authenticated="false" contrib-id-type="orcid">0000-0002-8174-2211</contrib-id>
  <name name-style="western">
    <surname>Milton</surname>
    <given-names>Martin J T</given-names>
  </name>
  <xref ref-type="aff" rid="affiliation01">1</xref>
</contrib>
```

So this means that there is a problem with parsing source XML -- is it this issue?
* https://github.com/relaton/relaton-bipm/issues/28

**Comment by andrew2net** [comment]
@ronaldtse I've updated the parser to solve this issue. This case is not a big problem. To be sure that the update won't cause other problems I've checked the what names there are in the rawdata-bipm-metrologia dataset. It revealed that there are many others problem with names consistency in the dataset.
So the question is: should I update the parser to solve only this issue or it's better to not parse names' parts and save fullnames as they are?

The relaton/relaton-bipm#2 issue is about documents duplications. I'll answer to your comment in the issue.

> So this means that there is a problem with parsing source XML -- is it this issue?
> 
> * [Parse BIPM Metrologia data from rawdata-bipm-metrologia relaton/relaton-bipm#28](https://github.com/relaton/relaton-bipm/issues/28)

**Comment by ronaldtse** [comment]
@andrew2net 

> I've checked the what names there are in the rawdata-bipm-metrologia dataset. It revealed that there are many others problem with names consistency in the dataset.

Can you point out what the inconsistencies are?

@MStock78120 and @jmilesBIPM would be interested in finding out the issues with the bibliographic encodings at Metrologia.

Thanks.

**Comment by andrew2net** [comment]
Some examples are here in format "given name", "surname" `file`:

- "I", "van Andel" `data/2022-04-05T10_55_52_content/0026-1394/0026-1394_43/0026-1394_43_5/0026-1394_43_5_426/met6_5_014.xml`
- "Adriaan M H", "van der Veen" `data/2022-04-05T10_55_52_content/0026-1394/0026-1394_47/0026-1394_47_1A/0026-1394_47_1A_08005/0026-1394_47_1A_08005.xml`
- "Mellisa Janse", "van Rensburg" `data/2022-04-05T10_55_52_content/0026-1394/0026-1394_49/0026-1394_49_1A/0026-1394_49_1A_08001/0026-1394_49_1A_08001.xml`
- "D", "Van Den Berghe" `data/2022-04-05T10_55_52_content/0026-1394/0026-1394_57/0026-1394_57_6/0026-1394_57_6_065032/met_57_6_065032.xml`
- "Adriaan M H van der", "Veen" `data/2022-04-05T10_55_52_content/0026-1394/0026-1394_49/0026-1394_49_6/0026-1394_49_6_702/met12_6_702.xml`
- "J Wouter van der", "Hout" `data/2022-04-05T10_55_52_content/0026-1394/0026-1394_54/0026-1394_54_1A/0026-1394_54_1A_08020/0026-1394_54_1A_08020.xml`
- "A M H van der", "Veen" `data/2022-04-05T10_55_52_content/0026-1394/0026-1394_55/0026-1394_55_1A/0026-1394_55_1A_08018/0026-1394_55_1A_08018.xml`
- "", "J de Boer" `data/2022-04-05T10_55_52_content/0026-1394/0026-1394_1/0026-1394_1_4/0026-1394_1_4_158/metv1i4p158.xml`
- "", "A De Marchi" `data/2022-04-05T10_55_52_content/0026-1394/0026-1394_14/0026-1394_14_4/0026-1394_14_4_179/metv14i4p179.xml`
- "", "J N de Souza Vianna" `data/2022-04-05T10_55_52_content/0026-1394/0026-1394_36/0026-1394_36_6/0026-1394_36_6_599/me9623.xml`
- "", "E De la cruz" `data/2022-04-05T10_55_52_content/0026-1394/0026-1394_40/0026-1394_40_1A/0026-1394_40_1A_04003/0026-1394_40_1A_04003.xml`
- "", "Ed W B de Leer" `data/2022-04-05T10_55_52_content/0026-1394/0026-1394_42/0026-1394_42_1A/0026-1394_42_1A_08003/0026-1394_42_1A_08003.xml`
- "P", "De Bièvre" `data/2022-04-05T10_55_52_content/0026-1394/0026-1394_44/0026-1394_44_1/0026-1394_44_1_1/met_44_1_1.xml`
- "Manuel", "de Jesús Avila Salas" `data/2022-04-05T10_55_52_content/0026-1394/0026-1394_47/0026-1394_47_1A/0026-1394_47_1A_08013/0026-1394_47_1A_08013.xml`
- "Elizandra", "Cananea de Sá Elias" `data/2022-04-05T10_55_52_content/0026-1394/0026-1394_51/0026-1394_51_1A/0026-1394_51_1A_08002/0026-1394_51_1A_08002.xml`
- "Suellen Cristina", "Sales Pereira de Sousa" `data/2022-04-05T10_55_52_content/0026-1394/0026-1394_51/0026-1394_51_1A/0026-1394_51_1A_08002/0026-1394_51_1A_08002.xml`
- "", "Conference Générale des Poids et Mesures; General Conference of Weights and Measures" `data/2022-04-05T10_55_52_content/0026-1394/0026-1394_4/0026-1394_4_3/0026-1394_4_3_147/metv4i3p147.xml`
- "", "Adriaan M H van der Veen" `data/2022-04-05T10_55_52_content/0026-1394/0026-1394_44/0026-1394_44_1A/0026-1394_44_1A_08001/0026-1394_44_1A_08001.xml`
- "", "Ed W B de Leer" `data/2022-04-05T10_55_52_content/0026-1394/0026-1394_44/0026-1394_44_1A/0026-1394_44_1A_08001/0026-1394_44_1A_08001.xml`
- "", "Manuel de Jesús Avila Salas" `data/2022-04-05T10_55_52_content/0026-1394/0026-1394_44/0026-1394_44_1A/0026-1394_44_1A_08001/0026-1394_44_1A_08001.xml`
- "", "R B Lee III" `data/2022-04-05T10_55_52_content/0026-1394/0026-1394_28/0026-1394_28_3/0026-1394_28_3_183/metv28i3p183.xml`
- "", "K v Klitzing" `data/2022-04-05T10_55_52_content/0026-1394/0026-1394_28/0026-1394_28_3/0026-1394_28_3_183/metv28i3p183.xml`
- "", "J -M Chartier" `data/2022-04-05T10_55_52_content/0026-1394/0026-1394_17/0026-1394_17_3/0026-1394_17_3_81/metv17i3p81.xml`
- "", "A-M Roux" `data/2022-04-05T10_55_52_content/0026-1394/0026-1394_10/0026-1394_10_3/0026-1394_10_3_99/metv10i3p99.xml`
- "", "H-J von Martens" `data/2022-04-05T10_55_52_content/0026-1394/0026-1394_40/0026-1394_40_1A/0026-1394_40_1A_09001/0026-1394_40_1A_09001.xml`
- "Ana", "Isabel Sanchez-Cabezudo" `data/2022-04-05T10_55_52_content/0026-1394/0026-1394_51/0026-1394_51_1A/0026-1394_51_1A_06021/0026-1394_51_1A_06021.xml`
- "W A M", "Wan Mohamed" `data/2022-04-05T10_55_52_content/0026-1394/0026-1394_46/0026-1394_46_3/0026-1394_46_3_315/met_46_3_315.xml`
- "Héctor A", "Castillo M" `data/2022-04-05T10_55_52_content/0026-1394/0026-1394_47/0026-1394_47_1A/0026-1394_47_1A_04009/0026-1394_47_1A_04009.xml`
- "José Noé", "Razo Razo" `data/2022-04-05T10_55_52_content/0026-1394/0026-1394_47/0026-1394_47_1A/0026-1394_47_1A_09003/0026-1394_47_1A_09003.xml`
- "Manuel de Jesús", "Avila Salas" `data/2022-04-05T10_55_52_content/0026-1394/0026-1394_48/0026-1394_48_1A/0026-1394_48_1A_08015/0026-1394_48_1A_08015.xml`
- "W B", "Silva Jr" `data/2022-04-05T10_55_52_content/0026-1394/0026-1394_50/0026-1394_50_1A/0026-1394_50_1A_08013/0026-1394_50_1A_08013.xml`
- "Robert D", "Vocke, Jr" `data/2022-04-05T10_55_52_content/0026-1394/0026-1394_51/0026-1394_51_1A/0026-1394_51_1A_08017/0026-1394_51_1A_08017.xml`
- "W B", "Silva Junior" `data/2022-04-05T10_55_52_content/0026-1394/0026-1394_51/0026-1394_51_1A/0026-1394_51_1A_08016/0026-1394_51_1A_08016.xml`
- "Manuel de", "Jesús Ávila Salas" `data/2023-01-27T03_01_52_content/0026-1394/0026-1394_60/0026-1394_60_1A/0026-1394_60_1A_08006/0026-1394_60_1A_08006.xml`

You can see that name parts can be all in surname or distributed between surname and given name unpredictably. Affixes can be capitalized or not. Even if we managed to make rules to parse forename, surname, initials, prefixes, and additions, I doubt that we'll be able to restore original name form the parts. I think if we use given-name + surname string as full name, it will give us original name. We have `fullname` element in our data model to keep the string.

FYI since the [issue](https://github.com/relaton/rawdata-bipm-metrologia/issues/5) we use branch `2023-04-23`

**Comment by ronaldtse** [comment]
@jmilesBIPM it seems that the Metrologia is the culprit -- can we request them to update this data to correct the names?

**Comment by jmilesBIPM** [comment]
The online version of the article in question (https://doi.org/10.1088/1681-7575/ab0013) displays the full name (given name plus surname) of all the authors correctly: e.g. "Martin J T Milton"
![image](https://github.com/metanorma/bipm-si-brochure/assets/105931640/85190025-de50-4f3e-b693-6521605fb056)

Isn't it possible for you just to display these two fields as provided in the XML files?

I see in the first message from @anermina that the XML gave
      <name>
        <forename language="en" script="Latn" initial="J">Martin</forename>
        <forename initial="T"/>
        <surname language="en" script="Latn">Milton</surname>
      </name>

This is admittedly more long winded than one might expect, but the answer seems to be

forename + forename initial given with forename + forename initial given separately + surname

= Martin J T Milton

**Comment by andrew2net** [comment]
@ronaldtse why don't we just save "given_name" + "surname" as a "fullname"? I don't think it's possible to parse all the names correctly.

**Comment by jmilesBIPM** [comment]
In that case we'd have "Martin T Milton" here? Close enough!

**Comment by andrew2net** [comment]
@jmilesBIPM in the source we have
```xml
<name name-style="western">
  <surname>Milton</surname>
  <given-names>Martin J T</given-names>
</name>
```
So "given-name" + "surname" will be "Martin J T Milton".

@ronaldtse I just noticed that there is "name-style" attribute. May be we can use it to parse name parts correctly.

**Comment by andrew2net** [comment]
There is only "western" name style.
Names now are created by concatenating "given-name" and "surname". The name now is "Martin J T Milton".
