### ISSUE TITLE
Review from BIPM to be addressed

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#24]
BIPM performed a review of the document and indicated the following issues to be fixed:

Page 3 :                “SI“ is missing at the end of the title
 
Page 4:                 ISBN number is missing
 
Page 5:                 wrong title “Résumé” instead of  “Le BIPM et la Convention du Mètre »
                               The list of member states in the margin begins too low and extends over two pages
                               The dots are missing in the list following the third paragraph
                               Much too large vertical space before the second list of bullet points
                               Dots are missing in the second list
 
Page 6:                 the numbers are missing in the list of Consultative Committees at the bottom of the page
 
Page 7:                 dots are missing in the list of bullet points in the middle of the page
 
Page 8:                 blue-red percent symbols between section numbers and titles
 
Page 9:                 All decisions of Annex 1 are listed separately
                               Annex 5 does not exist
 
Page 12:               The four paragraphs on the annexes 1 to 4 should be moved to the left.
                               In the original, the note has two paragraphs, the space has disappeared
 
Page 13:               The lines of the first paragraph are unequally spaced as a consequence of the superscripts
 
Page 15:               The notes in the margin should be vertically aligned with the top of the corresponding paragraph
                               In the second note in the margin the subscripts “-1” are too big
                               In the same note, the minus sign in the parentheses should be a superscript (-)
 
Page 16:               Table 1: the values of the Boltzmann and Avogadro constants are wrong.
 
Page 17:               the note in the margin is at the wrong place. It should be aligned with table 2 on the following page
                               The second part of this note, starting with “La commission…” is completely out of place. It belongs to page 29 (of the original)
                                The note following table 2 should not be there, it is a duplication of the note in the margin.
                              
A general comment is that the font chosen for the main text is not pleasant to read on a screen. It appears to be too bold and is not sharp.

CC @metanorma/editors @opoudjis @Intelligent2013 

The document under review was this: 
[20201006-si-brochure.zip](https://github.com/metanorma/bipm-si-brochure/files/5351606/20201006-si-brochure.zip)

------

We need to come up with fixes or explanations for those that can't/shouldn't be fixed.

**Comment by ronaldtse** [comment]
> A general comment is that the font chosen for the main text is not pleasant to read on a screen. It appears to be too bold and is not sharp.

Have sought clarification for this because the font seems identical.
<img width="1339" alt="Screen Shot 2020-10-09 at 6 50 56 AM" src="https://user-images.githubusercontent.com/11865/95521665-ac2d7180-09fc-11eb-8a30-d713c6a2fc01.png">


New file:
<img width="724" alt="image" src="https://user-images.githubusercontent.com/11865/95521718-cbc49a00-09fc-11eb-88ee-ff3e747e7b13.png">

Old file:
<img width="724" alt="Screen Shot 2020-10-09 at 6 53 32 AM" src="https://user-images.githubusercontent.com/11865/95521693-b3ed1600-09fc-11eb-8fc6-ce9944aea051.png">

**Comment by Intelligent2013** [comment]
### > Page 3 : “SI“ is missing at the end of the title

Fixed.

### > Page 4: ISBN number is missing

Source XML issue. ISBN should be determined in the `feedback-statement` element or in a separate element

```xml
  <feedback-statement>
    <p id="_43be9891-fb8f-487e-939d-c7b6cdc163bf">BIPM<br/>
      Pavillon de Breteuil<br/>
      F-92312 SГЁvres<br/>
      Cedex<br/>
      FRANCE</p>
  </feedback-statement>

```


### > Page 5: wrong title “Résumé” instead of “Le BIPM et la Convention du Mètre »

Source xml issue:

```xml
<abstract id="_le_bipm_et_la_convention_du_mètre"><title>Résumé</title><p id="_fe6dc838-cb21-4d8e-9994-2905eb0143df">Le Bureau international...
```

### > Page 5: The list of member states in the margin begins too low and extends over two pages

There was issue with list level notes, fixed. 


### > Page 5: The dots are missing in the list following the third paragraph

Fixed.

### > Page 5: Much too large vertical space before the second list of bullet points

For displaying first long side note in abstract I've changed algorithm for displaying it especially for brochure abstract. It may have side effect as described here https://stackoverflow.com/questions/64107954/how-to-vertical-align-text-bottom-for-long-table-in-xsl-fo if text will be changed in the future.

### > Page 5: Dots are missing in the second list

Fixed.

### > Page 6: the numbers are missing in the list of Consultative Committees at the bottom of the page

Fixed.

### > Page 7: dots are missing in the list of bullet points in the middle of the page

Fixed.

### > Page 8: blue-red percent symbols between section numbers and titles

I don't see it at my computer. I need a clarification. Could you attach a screenshot?


### > Page 9: All decisions of Annex 1 are listed separately

I need a difference in xml markup between decisions of Annex 1 and other level-2 sections (See Annexe 4, for example 'L’évolution historique de la réalisation des unités du SI')


### > Page 9: Annex 5 does not exist

Source xml  issue. In the source PDF there isn't Annex 5, but there is a standalone section 'Liste des sigles utilisés dans le présent volume'.


### > Page 12: The four paragraphs on the annexes 1 to 4 should be moved to the left.

In source xml issue these paragraph are usual paragraphs.


### > Page 12:  In the original, the note has two paragraphs, the space has disappeared

Fixed.


### > Page 13: The lines of the first paragraph are unequally spaced as a consequence of the superscripts

Fixed.

### > Page 15: The notes in the margin should be vertically aligned with the top of the corresponding paragraph

Fixed.


### > Page 15: In the second note in the margin the subscripts “-1” are too big

Xslt can't manage font-size for concrete element in mathml markup. May be jEuclid issue.


### > Page 15: In the same note, the minus sign in the parentheses should be a superscript (-)

Source xml issue. Should be enclosed in `sup`:
```xml
<p id="_1d7212a3-cdbc-4cd7-ac9c-d2c77de41420">Les quotients des unités SI peuvent être exprimés par une barre oblique (/) ou un exposant négatif (<sup>−</sup>).</p>
```


### > Page 16: Table 1: the values of the Boltzmann and Avogadro constants are wrong.

Source xml issue. Looks like these are copy-pasted values.



### > Page 17: the note in the margin is at the wrong place. It should be aligned with table 2 on the following page

Fixed.


### > Page 17: The second part of this note, starting with “La commission…” is completely out of place. It belongs to page 29 (of the original)

Fixed.


### > Page 17: The note following table 2 should not be there, it is a duplication of the note in the margin.

In the current version of XSLT, all table's notes display under the table only.



Latest PDFs:
[collection.presentation.pdf](https://github.com/metanorma/bipm-si-brochure/files/5355688/collection.presentation.pdf)
[collection.presentation_en.pdf](https://github.com/metanorma/bipm-si-brochure/files/5355705/collection.presentation_en.pdf)
[collection.presentation_fr.pdf](https://github.com/metanorma/bipm-si-brochure/files/5355714/collection.presentation_fr.pdf)

**Comment by opoudjis** [comment]
I am updating @Intelligent2013 with the latest generated brochure source XML, but he was up to date already. I am removing the issues he has already deem resolved:

Page 3 : “SI“ is missing at the end of the title. **Possibly invalid**

Page 4: ISBN number is missing


> Source XML issue. ISBN should be determined in the feedback-statement element or in a separate element

````
  <feedback-statement>
    <p id="_43be9891-fb8f-487e-939d-c7b6cdc163bf">BIPM<br/>
      Pavillon de Breteuil<br/>
      F-92312 SГЁvres<br/>
      Cedex<br/>
      FRANCE</p>
  </feedback-statement>
````

Page 5: wrong title “Résumé” instead of “Le BIPM et la Convention du Mètre »

>  Source xml issue:
````
<abstract id="_le_bipm_et_la_convention_du_mètre"><title>Résumé</title><p id="_fe6dc838-cb21-4d8e-9994-2905eb0143df">Le Bureau international...
````

Page 8: blue-red percent symbols between section numbers and titles **Needs clarification**

Page 9: All decisions of Annex 1 are listed separately

> I need a difference in xml markup between decisions of Annex 1 and other level-2 sections (See Annexe 4, for example 'L’évolution historique de la réalisation des unités du SI')

@Intelligent2013, I need clarification on this from you

Annex 5 does not exist

> Source xml issue. In the source PDF there isn't Annex 5, but there is a standalone section 'Liste des sigles utilisés dans le présent volume'.

Page 12: The four paragraphs on the annexes 1 to 4 should be moved to the left.

> In source xml issue these paragraph are usual paragraphs.

Page 15: In the second note in the margin the subscripts “-1” are too big

> Xslt can't manage font-size for concrete element in mathml markup. May be jEuclid issue.

In the same note, the minus sign in the parentheses should be a superscript (-)

Source xml issue. Should be enclosed in sup:

````
<p id="_1d7212a3-cdbc-4cd7-ac9c-d2c77de41420">Les quotients des unités SI peuvent être exprimés par une barre oblique (/) ou un exposant négatif (<sup>−</sup>).</p>
````

Page 16: Table 1: the values of the Boltzmann and Avogadro constants are wrong.

> Source xml issue. Looks like these are copy-pasted values.

Page 17: The note following table 2 should not be there, it is a duplication of the note in the margin.

> In the current version of XSLT, all table's notes display under the table only.

**Comment by Intelligent2013** [comment]
Page 9: All decisions of Annex 1 are listed separately

>> I need a difference in xml markup between decisions of Annex 1 and other level-2 sections (See Annexe 4, for example 'L’évolution historique de la réalisation des unités du SI')

> @Intelligent2013, I need clarification on this from you

@opoudjis In the source/original PDF, only `Annexe 4` has a sub-sectionss in ToC:

![изображение](https://user-images.githubusercontent.com/5559926/95675590-12fb8800-0bc1-11eb-9ee8-da70f3f79880.png)

In the source XML there isn't a difference in the structure of Annexe 1 and 4 and I can't determine in which case I should show sub-section in ToC and when not:

Annexe 1:
```xml
<annex id="_décisions_de_la_cgpm_et_du_cipm"
     		obligation="normative">
		<title>
			<strong>Annexe 1</strong>.<tab/>
			<strong>Décisions de la CGPM et du CIPM</strong>
		</title>
		...
		<clause id="_1re_cgpm_1889"
      			obligation="normative">
			<title depth="2">1.1.<tab/>1<sup>re</sup> CGPM, 1889</title>
```

Annexe 4:
```xml
<annex id="_notes_historiques_sur_lévolution_du_système_international_dunités_et_ses_unités_de_base"
     		obligation="normative">
		<title>
			<strong>Annexe 4</strong>.<tab/>
			<strong>Notes historiques sur l’évolution du Système international d’unités et ses unités de base</strong>
		</title>
		<clause id="_lévolution_historique_de_la_réalisation_des_unités_du_si"
      			obligation="normative">
			<title depth="2">4.1.<tab/>L’évolution historique de la réalisation des unités du SI</title>
```

**Comment by opoudjis** [comment]
> Page 9: All decisions of Annex 1 are listed separately

I know why they have done this, because there is a separate ToC for Annexe 1, but this inconsistency is so inane, I would rather we just not give them subsections under either. Introducing markup in Metanorma to say "have n levels of subsections for the ToC for Annex 1, but m levels of subsections for the ToC for Annex 4" is something we should NOT be putting into documents. @ronaldtse I will  not implement this unless forced to.

**Comment by opoudjis** [comment]
> Page 4: ISBN number is missing

https://github.com/metanorma/metanorma-standoc/issues/359

**Comment by opoudjis** [comment]
> Page 5: wrong title “Résumé” instead of “Le BIPM et la Convention du Mètre »

This section has been marked up as an abstract, and Metanorma policy is that abstract titles must be supplied, else they are not actually abstracts. I decree that in this instance they are not actually abstracts, and will change markup to generic preface section.

**Comment by opoudjis** [comment]
> Annex 5 does not exist

And indeed, the Metanorma document model does not provide for randomly putting an abbreviations section after appendixes, as BIPM has seen fit to do. In https://www.bipm.org/utils/common/documents/jcgm/JCGM_100_2008_E.pdf. the glossary is treated as a separate annex. 

I am not changing the document model of Metanorma and its 15 SDOs to indulge an exception that the BIPM does not even maintain consistently within its own documents. The abbreviations shall be an annex, I will just need to remove the "Annex" label from it by marking it up as unnumbered.

**Comment by ronaldtse** [comment]
It may be easier to encode it properly as a table of contents section.

**Comment by opoudjis** [comment]
Since it is not a table of contents section that is missing the Annex label but an abbreviations section, that is irrelevant.

**Comment by opoudjis** [comment]
> Page 12: The four paragraphs on the annexes 1 to 4 should be moved to the left.

They mean indent.

Metanorma uses semantic markup. It does not support indent. Metanorma is not Microsoft Word, to support random semantically ill-defined formatting, nor shall it become so. 

Indentation is justified by blockquote, which this is not, or by lists, which this is also not, or by types of admonition, which this is not.

Unless BIPM can provide a principled semantic semantic justification for an alternative, this shall be treated as an unordered list. Because clearly that's what this is. Changing markup accordingly.

**Comment by opoudjis** [comment]
> Page 15: In the same note, the minus sign in the parentheses should be a superscript (-)

Was correct in English text; fixed in French text.

**Comment by opoudjis** [comment]
> Page 16: Table 1: the values of the Boltzmann and Avogadro constants are wrong.

Was correct in English text; fixed in French text.

**Comment by opoudjis** [comment]
Page 17 issue with table marginal note has been addressed.

**Comment by opoudjis** [comment]
So, of the comments made by BIPM, we are currently declining to fix the following:

> A general comment is that the font chosen for the main text is not pleasant to read on a screen. It appears to be too bold and is not sharp.

The fonts are identical to the fonts in the source PDF.

> Page 8: blue-red percent symbols between section numbers and titles

Alex cannot see this in his PDF.

> Page 9: All decisions of Annex 1 are listed separately

Having tables of contents have different depths for different annexes is beyond the capability of Word, and we assume that BIPM are only achieving it by stitching together different Word documents. And while Annex 1 has its own ToC, it is a thematic ToC rather than a hierarchical one reflecting the order of clauses in the document. While it is easy enough to signal it as an arbitrary attribute on clauses, it is a bad idea for consistency, and we would recommend against it. 

> Page 12: The four paragraphs on the annexes 1 to 4 should be moved to the left.

They have been converted to a list. Metanorma does not support semantically unmotivated indentation, and a list is the closest there is to a semantically justified indentation.

> Page 15: In the second note in the margin the subscripts “-1” are too big

PDF Xslt can't manage font-size for concrete element in mathml markup. May be jEuclid issue.

Am updating Presentation XML and sending to @Intelligent2013 to render.

**Comment by opoudjis** [comment]
@ronaldtse is querying the necessity for a configurable ToC depth on clauses.

**Comment by ronaldtse** [comment]
@Intelligent2013 once the issues are all done can you help provide the latest PDFs? Thanks.

**Comment by manuel489** [comment]
Ok, I'm checking the PDF files provided by @Intelligent2013.
I'll be publishing any possible issue in separate tickets.

**Comment by manuel489** [comment]
> >A general comment is that the font chosen for the main text is not pleasant to read on a screen. It appears to be too bold and is not sharp.

> The fonts are identical to the fonts in the source PDF.

@opoudjis I partially agree with your statement. But I think I understand the why BIPM made that comment. Maybe the problem comes form the PDF viewer software. I'm using Acrobat Reader and the this is how it looks in some parts:

![issueFont2](https://user-images.githubusercontent.com/33627611/95928152-a504bb80-0d8e-11eb-9c34-f5fdeb04c42d.png)
(*left: original , right: generated*)

In the red square areas, notice how "Kcd" and "540x10^12 Hz" look more bold than original version. Here's another sample:

![issueFont3](https://user-images.githubusercontent.com/33627611/95928477-73402480-0d8f-11eb-915e-7b65efb98507.PNG)
(*left: original , right: generated*)

Apparently, this only happens in math expressions.  However, if I zoom into the bold text, it looks almost the same:

![issuefont4](https://user-images.githubusercontent.com/33627611/95928749-3d4f7000-0d90-11eb-9257-72772ea71f78.PNG)
(*left: original , right: generated*)

**Comment by opoudjis** [comment]
Right. The math expressions are going to be vulnerable to the different maths rendering engines that their PDF and our PDF have used.

**Comment by opoudjis** [comment]
@Intelligent2013 There's a lot of issues with keep-with-next, and they can be addressed in markup, for anything that's not a header; but headers need keep-with-next too, and I don't see that being observed in the Annex.

**Comment by opoudjis** [comment]
@ronaldtse You make the strategic call: my suggestion is that we may fix formatting to be perfect match, as with the minor issues @manuel489 raises, but that it should not be priority, given how much there is to do in general. The idiosyncrasies of BIPM in general are going to be onerous to maintain anyway, and need to be strategically resolved; spacing and size, by contrast, are easy fixes.

**Comment by ronaldtse** [comment]
I agree. Let's see how far @Intelligent2013 can push.

**Comment by Intelligent2013** [comment]
@manuel489 FYI
> 3. Resolution titles font size in Appendix 1 are larger that their parent clauses. (And they are not centered neither.)

Fixed:
![изображение](https://user-images.githubusercontent.com/5559926/96146364-e1f7bc00-0f0e-11eb-9ebe-cd474790799d.png)

**Comment by ronaldtse** [comment]
So the remaining issues are:
* Vertical gap caused by notes positioning in metanorma/mn-native-pdf#268
* Odd display of math font in Acrobat Reader #30

**Comment by Intelligent2013** [comment]
In Appendix 1 (SI-Brochure-9.pdf) there is a difference between list styles `a)` vs `(a)`:
in French (page 73), see a) as list label in the text body:
![изображение](https://user-images.githubusercontent.com/5559926/97039754-95972680-1575-11eb-8ded-652a81220a5f.png)


in English (page 181), see (a) as list label in the text body:
![изображение](https://user-images.githubusercontent.com/5559926/97039630-64b6f180-1575-11eb-87a1-12c437e4646a.png)
![изображение](https://user-images.githubusercontent.com/5559926/97039845-be1f2080-1575-11eb-97c5-d896be778a6f.png)

But in https://github.com/metanorma/metanorma-bipm/issues/32 they noticed `Page 6: in the original text, lists were not numbered but had letters (a), (b), (c), …`

We should exactly determine the format of list-labels.

**Comment by ronaldtse** [comment]
Thanks @Intelligent2013 , I have sought BIPM for clarification as described here: https://github.com/metanorma/metanorma-bipm/issues/32#issuecomment-715504754

**Comment by opoudjis** [comment]
> Thanks @Intelligent2013 , I have sought BIPM for clarification as described here: [metanorma/metanorma-bipm#32 (comment)](https://github.com/metanorma/metanorma-bipm/issues/32#issuecomment-715504754)

Issue resolved.

Vertical gap caused by notes positioning in metanorma/mn-native-pdf#268: resolved.

https://github.com/metanorma/bipm-si-brochure/issues/30: open but unassigned. No reason to keep this issue open.

**Comment by ronaldtse** [comment]
This issue will be kept open until BIPM reviews the results. @opoudjis says we will have them prepared by 2020-11-09.

**Comment by opoudjis** [comment]
Updated PDF:

[collection.pdf](https://github.com/metanorma/bipm-si-brochure/files/5509723/collection.pdf)

**Comment by anermina** [comment]
Please don't submit the generated file to BIPM yet. I've noticed some issues and will report them as soon as I finish re-checking the document.

**Comment by anermina** [comment]
I opened a new issue https://github.com/metanorma/bipm-si-brochure/issues/47 to address the noticed differences for French part of the brochure.  @opoudjis @Intelligent2013 @ronaldtse @manuel489 , please check. Thank you!

**Comment by anermina** [comment]
> This issue will be kept open until BIPM reviews the results. @opoudjis says we will have them prepared by 2020-11-09.

I think we can close this issue now. We have opened new ones after receiving comments from BIPM and they were discussed in separate tickets.
