### ISSUE TITLE
Last "triple check" on outstanding BIPM review items

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#240]
1. We noticed that in the number 9 192 631 770 which appears at several places, the first space between the “9” and the following three digits is missing.  This space existed in the previous version which you produced. This case is different from a single digit at the end, after the decimal point. In this case a group of four digits is formed as in 6.789 6868 (page 19 of English version). This is not done on the left side of a number.
 
2. We also found that small spaces between closing parenthesis and unit symbols, which existed in the previous version, have disappeared:
Page 18 (English version), first equation: “(…) s”
Page 18 (English version), second equation: “(…) m-2”
Page 19 (English version), first equation: “(…) s-1”
Page 19 (English version), third equation: “(…) kg”
Page 21 (English version), fourth equation: “(…) kg”
The same applies to the equivalent equations in the French version.
 
3. In the bibliography there seems to be a problem with the processing of Declarations – see for example references [65E/64F] and [74E/73F] – which are missing the format DECN as well as their details.
 
4. The form of the references for the meetings needs a minor adjustment in the French bibliography (e.g. p111)
 
![image001](https://github.com/user-attachments/assets/45e81f88-785b-41f8-a7eb-7d93f3a7c63a)

Here the “e” should be superscript and the “r” of réunion lower-case (both times): CIPM 43e réunion (1950)… 43e réunion du CIPM and ‘Comité international des poids et mesures’ (capital letter for Comité only)
 
5. There seems to be a problem with the form of the references to Metrologia. In both the English and French versions (e.g. p.107 [E] p.112 [F])  the information is repeated several times:
 
![image](https://github.com/user-attachments/assets/275f7c2c-0696-484a-8b22-96f1ecf76419)

Here I would have written simply
“J Terrien (1972) Metrologia 8(1) 32-36. doi 10.1088/0026-1394/8/1/006 “
 
6. There is a problem with the reference to the CIPM Declaration 1971-00 in the section on the 14th CGPM 1971 in the French version (p. 61) . As a consequence, this reference is missing in the French bibliography, whereas it is included as [14] in the English bibliography. Therefore, the French bibliograph has 111 entries, whereas the English has 112.
 
7. The majority of the Metrologia references are given with the author initial before the author name, whereas [107], [108] and [108] include the full first name rather than the initial (Andrew rather than A) and the last two [110, 111] list the initials after the surnames.
 
8. For the links in the text to the meetings and Resolutions in the French version (see for example p.40, p.102), the links should contain /fr/ in place of /en/
 
9. Is there a reason why the links to Metrologia in the Bibliography have not been made active?
 
10. The very last reference (no. 112 in the English text, no.111 in the French text) has a typo: it should be Milton M not Milton J.

**Comment by manuelfuenmayor** [comment]
@ronaldtse. From which output are these issues coming, version 2.01? Because, looking at v2.01, there are several cases where I don't see the described issue.

I proceed to go through every issue and present my comments...

## Issues 1 and 2
Yes, these issues are present in the latest update (v2.01).  It is not an encoding problem, though. I have generated outputs from the year 2022 that don't show this issue. @Intelligent2013 is this your area?

## Issue 3
Quote: *In the bibliography there seems to be a problem with the processing of Declarations – see for example references [65E/64F] and [74E/73F] – which are missing the format DECN as well as their details.*

I don't understand this description. What do you mean by "missing the format DECN as well as their details."?

In version 2.01, these are the [65E/64F] references:

![65e](https://github.com/user-attachments/assets/5999e8ab-de3f-486f-a32d-ebe944261ee1)
![64f](https://github.com/user-attachments/assets/b819d0ec-2486-41c9-be64-bdbcd19a6a14)

Perhaps these are not the related references.

## Issue 4
Quote: *The form of the references for the meetings needs a minor adjustment in the French bibliography (e.g. p111)*

Yes, I have it on reference 87, with a little different structure compared to image in the description:
![ref87](https://github.com/user-attachments/assets/4de522a6-a4ea-482a-b682-3eb8adc99d3a)

## Issue 5
Quote: *There seems to be a problem with the form of the references to Metrologia. In both the English and French versions (e.g. p.107 [E] p.112 [F]) the information is repeated several times:*

I don't see this problem on version 2.01:
![ref95](https://github.com/user-attachments/assets/76052103-f0be-4506-ab4b-3e191b2574ac)

## Issue 6
Quote: *There is a problem with the reference to the CIPM Declaration 1971-00 in the section on the 14th CGPM 1971 in the French version (p. 61) . As a consequence, this reference is missing in the French bibliography, whereas it is included as [14] in the English bibliography. Therefore, the French bibliograph has 111 entries, whereas the English has 112.*

(I guess you mean "CGPM Declaration 1971-00," not CIPM)

I don't see this issue in v2.01, here's the corresponding reference in French version:
![ref14](https://github.com/user-attachments/assets/ed8bd7e1-5e1b-4591-aa9a-8159dea4e719)

## Issue 7
Quote: *The majority of the Metrologia references are given with the author initial before the author name, whereas [107], [108] and [108] include the full first name rather than the initial (Andrew rather than A) and the last two [110, 111] list the initials after the surnames.*

Yes, I see this issue in v2.01 as well:
![ref92-94](https://github.com/user-attachments/assets/1b3a38af-59b1-4fbc-b4fa-812509033ba4)

## Issue 8
Quote: *For the links in the text to the meetings and Resolutions in the French version (see for example p.40, p.102), the links should contain /fr/ in place of /en/*

As stated in https://github.com/metanorma/bipm-si-brochure/issues/228, I only see this issue for Résolution du CIPM (1879). The rest of the references point their corresponding French version.

## Issue 9
Quote: *Is there a reason why the links to Metrologia in the Bibliography have not been made active?*

Perhaps I don't understand this question. In v2.01, Metrologia references contain active DOI links.

## Issue 10
Quote: *The very last reference (no. 112 in the English text, no.111 in the French text) has a typo: it should be Milton M not Milton J.*

These are the references that contain the name "Milton," in English version of 2.01:
![ref112-113](https://github.com/user-attachments/assets/ff196268-734d-4f46-9696-ca8198c69134)

Perhaps the reference 112 should contain "Milton M" instead of "Martin Milton"?

**Comment by ronaldtse** [comment]
@manuelfuenmayor all of these issues were previously raised and split into individual issues. Some of them have been properly resolved but as you can see, some are still not addressed. 

Furthermore, these issues were raised against the former 1.07 that we delivered to @MStock78120 and @jmilesBIPM . 2.01 was only done today, of course these issues were not raised from there, but as you can see they still apply.  

Issues 1 and 2 are @opoudjis . This needs to be urgently fixed. @manuelfuenmayor please help post this in metanorma-bipm as a new issue about BIPM number styling. 

Issue 3 we need to find out what the original references were to verify. 

All the rest need to be fixed too.

**Comment by manuelfuenmayor** [comment]
Summary of issues:

- [x] Issue 1: https://github.com/metanorma/bipm-si-brochure/issues/221
- [ ] Issue 2: https://github.com/metanorma/bipm-si-brochure/issues/222, https://github.com/plurimath/plurimath/issues/314
- [ ] Issue 3: https://github.com/metanorma/bipm-si-brochure/issues/223
- [ ] Issue 4: https://github.com/metanorma/bipm-si-brochure/issues/224
- [x] Issue 5: https://github.com/metanorma/bipm-si-brochure/issues/225
- [x] Issue 6: https://github.com/metanorma/bipm-si-brochure/issues/226
- [ ] Issue 7: https://github.com/metanorma/bipm-si-brochure/issues/227
- [x] Issue 8: https://github.com/metanorma/bipm-si-brochure/issues/228
- [x] Issue 9: https://github.com/metanorma/bipm-si-brochure/issues/229
- [x] Issue 10: https://github.com/metanorma/bipm-si-brochure/issues/230

**Comment by ronaldtse** [comment]
@MStock78120 @jmilesBIPM we're done!
