### ISSUE TITLE
BIPM and Manuel: Odd display of math font in Acrobat Reader

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#30]
> >A general comment is that the font chosen for the main text is not pleasant to read on a screen. It appears to be too bold and is not sharp.

> The fonts are identical to the fonts in the source PDF.

@opoudjis I partially agree with your statement. But I think I understand the why BIPM made that comment. Maybe the problem comes form the PDF viewer software. I'm using Acrobat Reader and this is how it looks in some parts:

![issueFont2](https://user-images.githubusercontent.com/33627611/95928152-a504bb80-0d8e-11eb-9c34-f5fdeb04c42d.png)
(*left: original , right: generated*)

In the red square areas, notice how "Kcd" and "540x10^12 Hz" look more bold compared to original version.
Here's another sample:

![issueFont3](https://user-images.githubusercontent.com/33627611/95928477-73402480-0d8f-11eb-915e-7b65efb98507.PNG)
(*left: original , right: generated*)

Apparently, this only happens in math expressions.  However, if I zoom into the bold text, it looks almost the same:

![issuefont4](https://user-images.githubusercontent.com/33627611/95928749-3d4f7000-0d90-11eb-9257-72772ea71f78.PNG)
(*left: original , right: generated*)

_Originally posted by @manuel489 in https://github.com/metanorma/bipm-si-brochure/issue_comments/708076317_

**Comment by Intelligent2013** [comment]
I've made some experiments with fonts. Results:
1. some glyphs in font STIX2Math look a bit thicker than Times New Roman (compare char `S` below).
2. jEuclid converts MathML into SVG paths (not text), therefore resulted SVG image in PDF looks thicker.
Here is discussed why jEuclid converts text to path: https://sourceforge.net/p/jeuclid/mailman/message/21997700/
```
> We have run into some more basis problems with the printed output -- the
> formulas seem blurred. I suspect this is because the text in the SVG is
> converted to paths, rather than being represented as text. Are there any
> tricks to acheiving better print output? (I'll email you a sample
> document separately.)
Yes, this is due to the conversion of fonts -> line graphics. On my
printer the formulas look a little bit thicker, but not blurry, and
actually look better than the rest of the text :)

The main reason for this conversion is that Fonts are handled very
differently by different systems - MathML has many dependencies on
special fonts and characters, and JEuclid has a smart
character-replacement strategy. For this to work, however, it must be
ensured that the font information known to JEuclid is EXACTLY the same
that is available to the final renderer - and this is where a lot of the
existing systems break. Even different versions of the same font may
have different characters available on different systems or when loaded
through different methods (such as ps-fonts vs. ttf fonts). Especially
with the two-step conversion (-> svg, -> pdf), we have two intermediate
renderers which again have their own font processing and metrics
definition. The only way out of this inconsistency was to let Jeuclid
also render the fonts.


```
3. Math equations in _source_ PDF looks identical as main text, because most chars typed by 'Times New Roman' font (as main text) and rendered in PDF as text (not paths).

Here is resulted PDF with a few math text representation:
[si-brochure-en.presentation.pdf](https://github.com/metanorma/bipm-si-brochure/files/5493891/si-brochure-en.presentation.pdf)

100%:
![изображение](https://user-images.githubusercontent.com/5559926/98233784-91550b00-1f70-11eb-86f9-46567cb0c293.png)

125%:
![изображение](https://user-images.githubusercontent.com/5559926/98233841-a03bbd80-1f70-11eb-938f-e398dc22294d.png)

150%:
![изображение](https://user-images.githubusercontent.com/5559926/98233913-b3e72400-1f70-11eb-8e3b-ecfc97678436.png)

300%:
![изображение](https://user-images.githubusercontent.com/5559926/98233965-cbbea800-1f70-11eb-8a98-99610218d10e.png)

**Comment by anermina** [comment]
Just to confirm that I get the same result as Manuel displayed in Adobe Acrobat Reader DC, version 2020.013.20066 (Windows OS).

Issue about different appearance of `stem:[cc(K)]` is probably caused by the same behavior as for the rest of the differences.
![image](https://user-images.githubusercontent.com/55683568/101486156-83721b80-395c-11eb-9f3d-91d55b455dc1.png)

**Comment by opoudjis** [comment]
@ronaldtse @Intelligent2013 Is this ticket actionable? It sounds like it isn't.

**Comment by ronaldtse** [comment]
BIPM's publication department is now reviewing the document, let's see if they notice this.

**Comment by ronaldtse** [comment]
We have not received complaints due to this. Closing.
