### ISSUE TITLE
BIPM feedback on MEP Kilogram

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/bipm-si-brochure#50]
We need to update the MEP Kilogram to the latest 2020-08-04 version.

From BIPM:

> The XML file has been produced from a previous verison of the mise en pratique.
> The current version on the web site dates from 4 August 2020.
> I will not comment on these changes in the following list.

Location  | Issue
-- | --
Title page | replace "9 édition 2020" by "9 édition 2019"
Title page | change date from 20 May 2020 to 04 August 2020
3 | replace "9th edition 2020" by "9th edition 2019"
3 | change date at bottom from 20 May 2020 to 04 August 2020
5 | first line:  link to reference should be [1]
5 | definition of kilogram: the numerical value is wrong, should be 6.626 070 15 x 10-34
  | replace comma in numerical value with dot
  | "c" in last line of definition should be invitalics
  | paragraph following definition: numerical value is wrong, should be 6.626 070 15 x 10-34
  | replace comma in numerical value with dot
  | end of second paragraph:replace "Clause 5" by "section 5"
6 | Second paragraph is not a part of the title of Figure 1. It should be vertically separated.
  | the link to reference should be [1]
7 | second paragraph of 3.1: g in italics
  | paragraph followin eq. 2: v in italics
  | equation 2: v in italics
  | equation 3: v in italics
  | last paragraph: v in italics
8 | equation 4: v in  italics
  | first pargraph of 3.2: lattice parameter a in italics
  | equation 5:  28Si (superscript)
  | line after equation 5: a(28Si)3
  | 2nd line after equation 5: a(28Si)3
  | 4th line after equation 5: a(28Si)3
  | equation 6: 28Si
  | equation 7: m(28Si) / h (compare with original)
  | line after equation 8: m(28Si)/h
9 | 3rd line: ms
  | the font different from that used before, but much better to read on my screen Can it be used everywhere
10 | first paragraph: replace "clause " by "section", also throughout the document
  | first paragraph: linebreak between 1 kg to be avoided.
12 | 3rd paragraph of 5.1: lines 4 and 6: h in italics
  | linebreak between 1 kg to be avoided.
  | replace comme in 1.0 with dot
13, 14 | wrong title in header
13 | reference [1]: replace with original text
  | reference [7]: replace h/mu with h/mu
  | Why is the number of the reference repeated at the end of each reference?
  | The usual way to number references in the bibliography is [n]
14 | Referece 24 is wrong, it should be for the 8th (!) edition of the SI brochure of 2006, see original mep
15 | Replace "Appendix" with "annex" throughout the document. All of these annexes are part of a document which is in Appendix 2 of hte SI brochure.
  | appendix 1: replace references with numbers
  | Table 1.1: p and q in title not in italics
  | last paragraph: first line: both letters of Cs are subscripts
  | last paragraph, second line: k in italics
16 | Note at beginning of section on atomic … units is missing. (I am not sure if this note has been added in the latest version of the mep, of 4 August 2020)
  | third line of section on atomic units: u not in  italics
  | 1.st paragraph: the reference to Appendix 1.4.1 is not working because you have removed the numbering of the sections of Annex 1.
  | Equations of physics, 3rd line: replace mu with mu
  | Equation 1.1: m(12C)
  | paragraph after equation 1.1: u not in italics
  | Equation 1.2: m(12C)
  | line above equation 1.3: replace second M(X) with m(X)
  | Equation 1.4: m(12C)
17 | paragraph following equation 1.7: replace comma in 4.5 with dot
  | second paragraph following equation 1.7: M(12C), M in italics
  | Item 3 of the list shall be item 3.a, item 3.b hase become item 1 of the next list
  | paragraph following list item 3: replace Mu with Mu
  | paragraph following list item 3: replace mol-1 with mol-1
  | paragraph following list item 3: replace comma in 4.5 with dot
  | list item 1 of second list shall be item 3.b of first list
18 | 2nd line: replace comma in 0.001 with dot
  | Equation 1.8: replace comma in 0.001 with dot
  | Equation 1.10: replace comma in number with dot
19 | 2nd last paragraph: a(Si)
20 | 3rd paragraph: second line: mi
21 | different font than page before, but looks much better.

@metanorma/editors if there are non-content issues, please ping @Intelligent2013 or @opoudjis . Thanks!

Original comment file if the math units are unclear here: 
[Observations mep kilogram.xlsx](https://github.com/metanorma/bipm-si-brochure/files/5548074/Observations.mep.kilogram.xlsx)

**Comment by manuel489** [comment]
Generated PDF reviewed by BIPM: [mep-kilogram-definition-en.presentation.pdf](https://github.com/metanorma/bipm-si-brochure/files/5554293/mep-kilogram-definition-en.presentation.pdf)

**Comment by manuel489** [comment]
Working on it...

**Comment by manuel489** [comment]
Almost all markup-related issues are fixed in https://github.com/metanorma/bipm-si-brochure/pull/55

These cases remain:

Location | issue | source
-- | -- | --
Title page | replace "9 édition 2020" by "9 édition 2019" | xslt
3 | replace "9th edition 2020" by "9th edition 2019" | xslt
5 | first line:  link to reference should be [1] | xslt
5 | definition of kilogram: the numerical value is wrong, should be 6.626 070 15 x 10-34 | xslt
  | paragraph following definition: numerical value is wrong, should be 6.626 070 15 x 10-34 | xslt
  | end of second paragraph:replace "Clause 5" by "section 5" | xslt
6 | Second paragraph is not a part of the title of Figure 1. It should be vertically separated. | xslt
  | the link to reference should be [1] | xslt
  | paragraph followin eq. 2: v in italics | xslt
  | equation 2: v in italics | xslt
  | equation 3: v in italics | xslt
  | last paragraph: v in italics | xslt
8 | equation 4: v in  italics | xslt
  | equation 5:  28Si (superscript) | xslt
  | equation 6: 28Si | xslt
  | line after equation 8: m(28Si)/h | xslt
  | the font different from that used before, but much better to read on my screen Can it be used everywhere | xslt
13, 14 | wrong title in header | xslt
  | Why is the number of the reference repeated at the end of each reference? | xslt
  | The usual way to number references in the bibliography is [n] | xslt
15 | Replace "Appendix" with "annex" throughout the document. All of these annexes are part of a document which is in Appendix 2 of hte SI brochure. | xslt
  | appendix 1: replace references with numbers | xslt
16 | Note at beginning of section on atomic … units is missing. (I am not sure if this note has been added in the latest version of the mep, of 4 August 2020) | xslt
  | 1.st paragraph: the reference to Appendix 1.4.1 is not working because you have removed the numbering of the sections of Annex 1. | xslt
  | Equation 1.1: m(12C) | xslt
  | Equation 1.2: m(12C) | xslt
  | Equation 1.4: m(12C) | xslt
  | list item 1 of second list shall be item 3.b of first list | xslt
21 | different font than page before, but looks much better. | xslt

Ping @Intelligent2013

**Comment by Intelligent2013** [comment]
> Title page | replace "9 édition 2020" by "9 édition 2019"
> 3 | replace "9th edition 2020" by "9th edition 2019"

This is a bibdata issue.

'2020' is a value from source xml `bibdata/copyright/from`.
```xml
<from>2020</from>
```

Also there is a field `bibdata/version/revision-date`:
```xml
<revision-date>2020-05-20</revision-date>
```

But in bibdata there isn't any field with value '2019'.

> 6 | Second paragraph is not a part of the title of Figure 1. It should be vertically separated.

Fixed.

> 8  | equation 5:  28Si (superscript)
> 8  | equation 6: 28Si
> 8  | line after equation 8: m(28Si)/h

Fixed.

> 8  | the font different from that used before, but much better to read on my screen Can it be used everywhere

I didn't understand it.


> 13, 14 | wrong title in header

Header 'Continuity with the previous definition of the kilogram' shows instead of 'Bibliography', because section '5.3 Bibliography' is a part of section '5. Continuity with the previous definition of the kilogram'. I put only main section title in the header.
In the source PDF Bibliography (References) is a standalone section.

> | Why is the number of the reference repeated at the end of each reference?
> | The usual way to number references in the bibliography is [n]

In xslt I didn't realize displaying well-formed bibliography via xslt. @ronaldtse should I repeat the logic from ruby in xslt to display references? Or this task relates to presentation xml?


> 15 | Replace "Appendix" with "annex" throughout the document. All of these annexes are part of a document which is in Appendix 2 of hte SI brochure

This is not xslt task.



> 16 | Note at beginning of section on atomic … units is missing.

Issue: https://github.com/metanorma/mn-native-pdf/issues/282


> 16  | 1.st paragraph: the reference to Appendix 1.4.1 is not working because you have removed the numbering of the sections of Annex 1.

The reference points to 'Equations of physics' and it's working. Confusing occurs due section number`1.4.1` doesn't showing at section 'Equations of physics'. I can't figure out what should I do here. BIPM xslt uses common style for brochure and mep.

> 16  | Equation 1.1: m(12C)
> 16  | Equation 1.2: m(12C)
> 16  | Equation 1.4: m(12C)

Fixed.

> 21 | different font than page before, but looks much better.

I can't repeat it. All pages displays by one font.

**Comment by Intelligent2013** [comment]
> 16 | Note at beginning of section on atomic … units is missing.

Fixed.

**Comment by opoudjis** [comment]
> 5  | end of second paragraph:replace "Clause 5" by "section 5"

This is BIPM inconsistency, and we will not perpetuate it.

https://www.bipm.org/utils/common/pdf/si-brochure/SI-Brochure-9-EN.pdf, p. 130:

<img width="250" alt="Στιγμιότυπο 2020-11-24, 22 38 25" src="https://user-images.githubusercontent.com/1911039/100089801-5e82a080-2ea6-11eb-90ac-6edd5f93a32f.png">

https://www.bipm.org/utils/en/pdf/si-mep/SI-App2-kilogram.pdf, p. 1

<img width="1040" alt="Στιγμιότυπο 2020-11-24, 22 39 36" src="https://user-images.githubusercontent.com/1911039/100089553-f6cc5580-2ea5-11eb-976f-8d1a52469510.png">

The rule in the Brochure, which BIPM has been repeatedly complaining about in feedback, is that clauses are Chapter, and subclauses are Section.

BIPM have provided no justification for that rule applying to the Brochure, and not to mises en pratique. It is possible that they are come up with some notion that clauses in the Brochure are _chapters_, and clauses in smaller documents are _sections_. Such frivolous inconsistency is hard for me to take seriously when it is not articulated in any documentation, and I shall not be implementing it unless asked to explicitly. With an actual rule for where chapters apply.

**Comment by opoudjis** [comment]
> 6  | paragraph followin eq. 2: v in italics
> 6  | equation 2: v in italics
> 6  | equation 3: v in italics
> 6  | last paragraph: v in italics
> 8 | equation 4: v in  italics

The issue of selective italicisation of parts of equations will ultimately need to be addressed by some form of Units Markup (https://github.com/metanorma/metanorma-bipm/issues/3), and is currently to be addressed by introducing an upright font shift in Asciimath: https://github.com/metanorma/bipm-si-brochure/issues/54.

**Comment by opoudjis** [comment]
> 5 | first line:  link to reference should be [1]
> 5 | definition of kilogram: the numerical value is wrong, should be 6.626 070 15 x 10-34
> 5  | paragraph following definition: numerical value is wrong, should be 6.626 070 15 x 10-34
> 6  | the link to reference should be [1]

Now fixed

> 17 | Item 3 of the list shall be item 3.a, item 3.b hase become item 1 of the next list
> 17  | list item 1 of second list shall be item 3.b of first list

3a and 3b are not real list numbers, but more of BIPM's wilfulness. I will note that this is clearly a Word document, and they just as clearly have not used Word list numbering, because after all, Word cannot generate list numbers like "3a" and "3b".

Neither can HTML.

_Neither shall we_. @manuel489 Please change markup here: these are simply not list numbers, but numbers at the start of paragraphs.

**Comment by opoudjis** [comment]
> 15  | appendix 1: replace references with numbers

SI Brochure is fixed, but mises en pratique still referenced by identifier.

And that is because the references in source are using the identifiers. They need to be numbers, like the others are; we can preserve both the number and the identifier as described in https://www.metanorma.com/author/topics/document-format/bibliography/#named-reference-tag-with-automatic-reference-fetching

The reference numbering in the source PDF follows a baroque numbering scheme, 2.1, 2.2, 3.1, etc—which we can replicate in the references. I have fixed the source.

If you want to replicate this baroque scheme, (a) you will need to change markup from

`* [[[bipm-si-brochure,1]]] BIPM, The International System of Units (SI Brochure) [9^th^ edition, 2019], https://www.bipm.org/en/publications/si-brochure/.`

to 

`* [[[bipm-si-brochure,2.1]]] BIPM, The International System of Units (SI Brochure) [9^th^ edition, 2019], https://www.bipm.org/en/publications/si-brochure/.`

(b) I will need to recognise references like 2.1 and A1.1 as not standard identifiers, but numeric identifiers, to be put in square brackets. I would much rather BIPM be talked out of this supremely impractical, counterintuitive, home-brew scheme for referencing.

(c) @Intelligent2013 will need to overhaul how he generates references, to ignore incremental numbering, and use the provided `docidentifier[@type = 'metanorma']` identifiers instead.

That is a lot of work for us, for something I see little justification in.

**Comment by opoudjis** [comment]
From @Intelligent2013 

>> Why is the number of the reference repeated at the end of each reference?
>> The usual way to number references in the bibliography is [n]

> In xslt I didn't realize displaying well-formed bibliography via xslt. @ronaldtse should I repeat the logic from ruby in xslt to display references? Or this task relates to presentation xml?

Ronald is pretty adamant that it relates to Presentation XML; but incorporating `docidentifier` into `formattedref` is significant refactoring, and it is going to have to wait.

>> 15 | Replace "Appendix" with "annex" throughout the document. All of these annexes are part of a document which is in Appendix 2 of hte SI brochure

> This is not xslt task.

It's mine. We are being forced to change the section label of appendixes if the document has an appendix identifier.

**Comment by manuel489** [comment]
Based on latest PDF provided by @opoudjis: [mep-kilogram-definition-en.pdf](https://github.com/metanorma/bipm-si-brochure/files/5649718/mep-kilogram-definition-en.pdf)


Issues fixed recently:

Location | Comment | Issue
-- | -- | --
13, 14 | wrong title in header | fixed in https://github.com/metanorma/bipm-si-brochure/pull/59
  | second paragraph following equation 1.7: M(12C), M in italics | fixed in https://github.com/metanorma/bipm-si-brochure/pull/59


Remaining issues:

Location | Comment | Issue
-- | -- | --
Title page | change date from 20 May 2020 to 04 August 2020 | not fixed: *it says "April 08" instead of "August 04"*
3 | change date at bottom from 20 May 2020 to 04 August 2020 | not fixed: *it says "08 April 2020" instead of "04 August 2020"*
  | end of second paragraph:replace "Clause 5" by "section 5" | will not fix, https://github.com/metanorma/bipm-si-brochure/issues/50#issuecomment-732889277
  | paragraph followin eq. 2: v in italics | not fixed
  | equation 2: v in italics | not fixed
  | equation 3: v in italics | not fixed
  | last paragraph: v in italics | not fixed
8 | equation 4: v in  italics | not fixed
  | Why is the number of the reference repeated at the end of each reference? | not fixed
  | The usual way to number references in the bibliography is [n] | not fixed
21 | different font than page before, but looks much better. | will not fix, https://github.com/metanorma/bipm-si-brochure/issues/50#issuecomment-729645342

**Comment by manuel489** [comment]
> equation 3: v in italics | not fixed

@opoudjis, this problem refers to: 
````
[stem]
++++
m_x g vee = I_1 U_2
++++
````

being rendered as:
![Capture](https://user-images.githubusercontent.com/33627611/101296065-c666ae80-37f7-11eb-8b79-ad189ac166bf.PNG)


instead of: 
![Capture2](https://user-images.githubusercontent.com/33627611/101296079-ce265300-37f7-11eb-98bd-548ead45f808.PNG)

The `vee` is not italicized. Should I change the markup to `ii(vee)` in order to fix?

**Comment by manuel489** [comment]
Also, `stem:[N]` has become upright:

````
[stem]
++++
ii(M)("X") = m("X") N_"A" = A_"r" ("X") m_{rm(u)} N_"A"
++++
````

Before:
![Capture3](https://user-images.githubusercontent.com/33627611/101297270-89ea8100-37fe-11eb-8b8c-9ce218122aad.PNG)

Now:
![Capture4](https://user-images.githubusercontent.com/33627611/101297276-8eaf3500-37fe-11eb-82c2-f5b36ef7f597.PNG)

**Comment by opoudjis** [comment]
> not fixed: it says "08 April 2020" instead of "04 August 2020"

The revdate has been entered as 2020-04-08 in Asciidoctor source. _That is April 8_. Fixing.

**Comment by anermina** [comment]
As I can see, remaining issues were discussed in https://github.com/metanorma/bipm-si-brochure/issues/52. Therefore, closing this ticket.

>13 | Why is the number of the reference repeated at the end of each reference? | not fixed
>  | The usual way to number references in the bibliography is [n] | not fixed
-- | -- | --
