### ISSUE TITLE
Recommended values: generating title and subtitle

### ISSUE THREAD

**Issue by anermina** [metanorma/bipm-si-brochure#89]
In rec-values documents, part title and its "subtitle" are currently generated in a separate section.

Generated:
![image](https://user-images.githubusercontent.com/55683568/110867232-c1b60880-82c6-11eb-871e-63e71a0d8415.png)
 
Original:
![image](https://user-images.githubusercontent.com/55683568/110867278-c975ad00-82c6-11eb-8476-f4916e3d61b4.png)

Since this is quite different from the original document, can we use something like this instead:
`:title-part-en: Rubidium 87 Atom (stem:[f ~~ 6.835"unitsml(GHz)"])`
`:title-subpart-en: ^87^Rb, unperturbed ground-state hyperfine transition`
or some other solution?

**Comment by opoudjis** [comment]
The markup problem is that you've inserted an artificial clause heading to put in a paragraph that is unassociated with any clause:

````
== Rubidium 87 Atom (stem:[f ~~ 6.835" "rm(GHz)])

*^87^Rb, unperturbed ground-state hyperfine transition*
````

We allow admonitions and notes that precede the first clause, but neither will give us the desired rendering. That is of course because this is an ill-considered violation of well-structured text: it's a "discrete heading", a heading outside the section hierarchy.

The following markup is Dodgy AF, but... it will work. I would rather the document be rephrased, but you can use:

````
[%unnumbered]
== {blank}

*^87^Rb, unperturbed ground-state hyperfine transition*
````
