### ISSUE TITLE
Brochure review: white spacing before deg symbol

### ISSUE THREAD

**Issue by manuel489** [metanorma/bipm-si-brochure#96]
*In relation to https://github.com/metanorma/bipm-si-brochure/issues/87*

There is still white spacing before `deg` unitsml symbol. For example, for `stem:[90 "unitsml(deg)"]`:

![issue2-generated](https://user-images.githubusercontent.com/33627611/111406965-87bf7a80-86a9-11eb-9c81-107351003d63.PNG)

In addition, there is also white space when a division symbol (`/`) is in front of the unitsml block. For example, for `stem:[u_c//"unitsml(MHz)"]`

![issue1-generated](https://user-images.githubusercontent.com/33627611/111407481-3bc10580-86aa-11eb-8b1b-40fe7b7e3c41.PNG)

(Same happens when `cdot` symbol is in front.)

**Comment by opoudjis** [comment]
Well, this is going to be subtle.

We have a problem that https://github.com/metanorma/metanorma-standoc/issues/441 over-relaxed the constraints on space: we want a space after `(3)`, but not after `/`.

I have two alternatives here: either use the semantics of MathML (to the extent they are correct), or introduce an option to suppress space insertion.

I'm going to try the former, because I think it will work. So initially, we inserted space only between `mn` (numeral) and a unit. Now we insert space between anything and a unit. I will change this to insert space between anything other than `mo` (an operator) and a unit. That will also take care of cdot.

**Comment by opoudjis** [comment]
The degree symbol was wrong in the unitsdb tables: it was entered not as &#xB0;, the degree sign °, which is a symbol, but as &#xBA;, the masculine ordinal sign º (as in _1º_, read "prim-o"), which is alphabetic. Because it is alphabetic, space is being inserted before it.
