### ISSUE TITLE
Brochure review: unbalanced exponent alignment in steradian symbol

### ISSUE THREAD

**Issue by manuel489** [metanorma/bipm-si-brochure#99]
*In relation to https://github.com/metanorma/bipm-si-brochure/issues/87*

Exponents upon steradian unit symbol is being rendered too low making it look misaligned respect to other exponents.

From *mep-candela-rapport-en.pdf:*
![issue2-generated](https://user-images.githubusercontent.com/33627611/111410704-990b8580-86af-11eb-8180-cac54ded743f.PNG)

From *mep-kelvin-absolute-en*, there is this case as well:

![exponent-issue](https://user-images.githubusercontent.com/33627611/111412607-1389d480-86b3-11eb-81e2-a4bc1049bd60.PNG)

**Comment by Intelligent2013** [comment]
@manuel489 I can't repeat this issue. Could you attach a source presentation XMLs for both documents, please?

In my environment it renders ok:
![изображение](https://user-images.githubusercontent.com/5559926/111446565-98a9d380-871d-11eb-875d-f21cb34407f0.png)

Actually, this issue was fixed a few weeks ago...

**Comment by Intelligent2013** [comment]
@manuel489 for mep-candela-rapport-en.pdf I've found xml in another issue.

**Comment by Intelligent2013** [comment]
Fixed.
![изображение](https://user-images.githubusercontent.com/5559926/111456581-3904f580-8728-11eb-8879-8f5129a6f3b9.png)

**Comment by manuel489** [comment]
Thanks!
